### ISSUE TITLE
List

### ISSUE THREAD

**Issue by catalin-stancu** [alexandruradovici/alf-alfy-language-public#1]
**array list of string from 1 to 9;

define v => list;**    --> here, from what I've seen in the AST "list" is a type, so... are we supposed to have a token for the type list? Because if we make a token for type list, when we declare an array named "list", it will say that it expects Identifier but got List. Or this statement "define v => list;"  means something like this? 
var arr1 = ['a','b','c'];
var arr2 = arr1; ?

**Comment by alexandruradovici** [comment]
The type may be either any of the predefined types or any other type that you define as an array or a struct. For this homework, you may suppose that any word is a valid type as type, regardless if it is or not defined as a type.
