### ISSUE TITLE
function parameters

### ISSUE THREAD

**Issue by catalin-stancu** [alexandruradovici/alf-alfy-language-public#2]
https://github.com/alexandruradovici/alf-alfy-language-public/blob/master/verify/alfy/4_function/do_function_with_expression.alfy.json

Here, the parameters aren't supposed to be in an array? and also aren't they supposed to be reversed? Because if i don't put them in an array, only one parameter will be put in the AST and i don't get it

**Comment by alexandruradovici** [comment]
The parameters are for the function run and are in a dictionary as they are supplied as "id is value". The order does not matter and if a parameter is supplied twice, the first is the value that will be put.
